apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  priorityClassName: postgres-high-priority
  instances: 1
  envFrom:
  - configMapRef:
      name: app-config
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
