apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ copier__rfc1123_subdomain }}-prod

resources:
  - ../sandbox
  - secrets.yaml

patches:
- target:
    kind: SealedSecret
    name: secrets-config
  path: secrets.yaml
- patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: letsencrypt-prod
    - op: replace
      path: /spec/dnsNames
      value:
        - api.{{ copier__domain_name }}
        - k8s.{{ copier__domain_name }}
  target:
    kind: Certificate
    name: cluster-cert
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`api.{{ copier__domain_name }}`)
  target:
    kind: IngressRoute
    name: backend-ingress
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`k8s.{{ copier__domain_name }}`)
  target:
    kind: IngressRoute
    name: k8s-ingress
- patch: |-
    - op: replace
      path: /spec/backup/barmanObjectStore/destinationPath
      value: "s3://{{ copier__project_dash }}-prod-backups/"
  target:
    kind: Cluster
    name: postgres
{% if copier__create_nextjs_frontend %}
- patch: |-
    - op: add
      path: /data/DISTRIBUTION_ID
      value: "CHANGEME"
  target:
    kind: ConfigMap
    name: app-config{% endif %}

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="production"
     - DJANGO_SETTINGS_MODULE="config.settings.production"
     - DJANGO_CSRF_TRUSTED_ORIGINS="https://{{ copier__domain_name }}"
     - AWS_S3_CUSTOM_DOMAIN="{{ copier__domain_name }}"

images:
  - name: {{ copier__aws_account_id }}.dkr.ecr.{{ copier__aws_region }}.amazonaws.com/{{ copier__project_dash }}-sandbox-backend
    newName: {{ copier__aws_account_id }}.dkr.ecr.{{ copier__aws_region }}.amazonaws.com/{{ copier__project_dash }}-backend
    newTag: latest
{% if copier__create_nextjs_frontend %}
  - name: {{ copier__aws_account_id }}.dkr.ecr.{{ copier__aws_region }}.amazonaws.com/{{ copier__project_dash }}-sandbox-frontend
    newName: {{ copier__aws_account_id }}.dkr.ecr.{{ copier__aws_region }}.amazonaws.com/{{ copier__project_dash }}-frontend
    newTag: latest{% endif %}
