name: Test template

on:
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Copier
        shell: bash
        run: |
          pip install copier

      - name: Test Template
        shell: bash
        run: |
          echo "Installing template from $GITHUB_HEAD_REF"
          copier copy \
          --trust \
          --defaults \
          --skip-tasks \
          --vcs-ref=$GITHUB_HEAD_REF \
          https://github.com/sixfeetup/scaf-fullstack-template.git test-project
