name: Test template

on:
  pull_request:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  test-template:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'template/frontend/package*.json'

      - name: Install kind
        shell: bash
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install copier black isort

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Template Test"

      - name: Test Template
        shell: bash
        env:
          VCS_REF: ${{ github.head_ref || github.ref_name || github.sha }}
        run: |
          echo "Installing template from ${VCS_REF}"
          copier copy \
          --trust \
          --defaults \
          --vcs-ref=${VCS_REF} \
          https://github.com/sixfeetup/scaf-fullstack-template.git test-project

      - name: Run lint and formatting checks
        shell: bash
        run: |
          cd test-project
          make check-lint-and-formatting

      - name: Run frontend lint and tests
        shell: bash
        run: |
          cd test-project
          make check-lint-and-test-frontend

      - name: Install Tilt
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
          tilt version

      - name: Run Tilt CI
        shell: bash
        run: |
          set -euo pipefail
          cd test-project
          tilt ci

      - name: Notify Slack on Success
        if: success() && github.event_name == 'schedule'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Daily template test completed successfully! ✅"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Daily template test completed successfully! ✅"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Repository*: ${{ github.repository }}"
                  - type: "mrkdwn"
                    text: >
                      *Run Details*: 
                      <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>

      - name: Notify Slack on Failure
        if: failure() && github.event_name == 'schedule'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Daily template test failed! ❌"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Daily template test failed! ❌"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Please check the workflow logs for more information."
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Repository*: ${{ github.repository }}"
                  - type: "mrkdwn"
                    text: >
                      *Run Details*: 
                      <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>
