name: Test template

on:
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'template/frontend/package*.json'

      - name: Install kind
        shell: bash
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install copier black isort

      - name: Test Template
        shell: bash
        run: |
          echo "Installing template from $GITHUB_HEAD_REF"
          copier copy \
          --trust \
          --defaults \
          --vcs-ref=$GITHUB_HEAD_REF \
          https://github.com/sixfeetup/scaf-fullstack-template.git test-project
